# Generated by Django 3.2.3 on 2021-06-03 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Title', max_length=255, unique=True, verbose_name='Title')),
                ('createdat', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('tag', models.CharField(choices=[('news', 'news'), ('analytics', 'analytics'), ('breaking', 'breaking')], default='news', max_length=15, verbose_name='Tag')),
                ('image_url', models.CharField(default='/beyondf1.jpg', max_length=512, verbose_name='Image url')),
                ('text', models.TextField(default='Text', max_length=255, unique=True, verbose_name='Text')),
                ('source', models.CharField(default='beyondf1.com', max_length=512, verbose_name='Source')),
            ],
        ),
    ]
