# Generated by Django 3.2.3 on 2021-06-03 05:06

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_articles_article'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='text',
            field=ckeditor.fields.RichTextField(default='Text', verbose_name='Text'),
        ),
    ]
